services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=sqlite
      - SQLITE_DB_PATH=./book_recommendation.db
      - SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: poetry run celery -A app.tasks.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DB_TYPE=sqlite
      - SQLITE_DB_PATH=./book_recommendation.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis